---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-web-ui
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.webui.replicas}}
  selector:
    matchLabels:
      app: tb-web-ui
  template:
    metadata:
      labels:
        app: tb-web-ui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - tb-web-ui
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tb-web-ui
          imagePullPolicy: IfNotPresent
          image: {{.Values.webui.image}}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.webui.resources | nindent 12}}
          env:
            - name: HTTP_BIND_ADDRESS
              value: "0.0.0.0"
            - name: HTTP_BIND_PORT
              value: "8080"
            - name: TB_ENABLE_PROXY
              value: "false"
            - name: LOGGER_LEVEL
              value: "info"
            - name: LOG_FOLDER
              value: "logs"
            - name: LOGGER_FILENAME
              value: "tb-web-ui-%DATE%.log"
            - name: DOCKER_MODE
              value: "true"
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 10
      nodeSelector:
        {{.Values.webui.nodeSelector}}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tb-web-ui
  namespace: {{.Values.namespace}}
  labels:
    app: tb-web-ui
spec:
  type: ClusterIP
  selector:
    app: tb-web-ui
  ports:
    - port: 8080
      name: http
